### ISSUE TITLE
Private key

### ISSUE THREAD

**Issue by mrquincle** [alexderidder/CassandraJSConnector#1]
Hi Alex! 

Thanks for the hard work during your internship. I'll use here and there definitely parts of it. 

Note that there's a private key in:

https://github.com/alexderidder/CassandraJSConnector/blob/master/middleware/config.security.js

It's only used on your local machine of course, but I thought to point it out anyway. :-)

Cheers!

**Comment by alexderidder** [comment]
Hi! 

Oh thanks, the keys aren't used anymore. Just ask if something isn't clear.

Good luck!
